# Este arquivo vai criar um banco do tipo postgres no docker.
version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wallace
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    ## Caso queira usar algum script sql para criar tabelas, descomente a linha abaixo e crie o arquivo init.sql
    ## volumes:
      ## - ./init.sql:/docker-entrypoint-initdb.d/init.sql